version: "3.8"
services:
  karate-test:
    image: maven:3.8-openjdk-17
    entrypoint: /app/entrypoint.sh
    working_dir: /app
    volumes:
      - .:/app
      - maven-repo:/root/.m2
      - karate-report:/report

  apache-report:
    image: httpd
    depends_on:
      - karate-test
    ports:
      - "8000:80"
    volumes:
      - karate-report:/usr/local/apache2/htdocs
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf

  nginx-report:
    image: nginx:1.14
    depends_on:
      - karate-test
    ports:
      - "8080:80"
    volumes:
      - karate-report:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  maven-repo:
  karate-report: