name: Karate API test
on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  maven-test:
    runs-on: ubuntu-latest
    name: Run tests with Karate

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Run Tests with Maven
        run: mvn clean test

      - name: Test report
        uses: ScaCap/action-surefire-report@v1.0.5
        if: always()
        with:
          check_name: Maven Test Summary Report
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "target/surefire-reports/TEST-*.xml"

      - name: JUnit Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit Test Report
          path: target/surefire-reports/**/TEST-*.xml
          reporter: java-junit
          fail-on-error: 'false'

      - name: Copy index file to cucumber report dir
        if: always()
        run: cp index.html target/cucumber-html-reports/

      - name: Publish generated content to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
        with:
          email: deploy@githubactions.net
          build_dir: target/cucumber-html-reports/
          branch: gh-pages

      - name: Cucumber report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: "target/cucumber-html-reports/*"